### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-ec#7]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

This is part of the GoLive activities.

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="0fe36564-e6c9-457f-84d8-d4eccfb7b7d5" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>
