### ISSUE TITLE
GoLive Activities Checklist - MackTrucks EC

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-ec#8]
Checklist of all activities needed for the GoLive of MackTrucks EC:

**Preparation tasks**
- [ ] #1 

**Pre, during, and post-GoLive:**
- [ ] #2 

**Pre-GoLive:**
- [ ] #3 
- [ ] #4 
- [ ] #5 
- [x] #6 
- [x] #7 
- [ ] [AEM GoLive steps](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- Legacy redirects
- Favicon
- CDN configuration
- Update production host

**Post-GoLive:**
- [ ] [AEM Post-GoLive Validation](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- 404 Report

**Comment by Kannan-CM** [comment]
Content Migrated and the site is live
